service: python-version

provider:
  name: aws
  runtime: python2.7
  region: us-west-2

functions:
  analyze:
    handler: handler.analyze
    events:
      - http:
          path: ping
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
